media:
  input: images
  output: /images

content:
  - name: news
    label: News
    type: file
    path: news.json
    fields:
      - name: items
        label: News list
        type: object
        list: true
        fields:
          - name: date
            label: Date
            type: date
          - name: title_en
            label: Title - English
            type: string
          - name: title_ru
            label: Title - Russian
            type: string
          - name: title_sr
            label: Title - Serbian (latinica)
            type: string
          - name: link
            label: Link (optional)
            type: string

  - name: events
    label: Events
    type: file
    path: events.json
    fields:
      - name: items
        label: Events list
        type: object
        list: true
        fields:
          - name: date
            label: Course date
            type: date
          - name: title_en
            label: Course title - English
            type: string
          - name: title_ru
            label: Course title - Russian
            type: string
          - name: title_sr
            label: Course title - Serbian (latinica)
            type: string
          - name: details_en
            label: City and details - English
            type: string
            description: "Example: Pozarevac, Serbia - 2 days"
          - name: details_ru
            label: City and details - Russian
            type: string
          - name: details_sr
            label: City and details - Serbian
            type: string
